require_relative '../node_modules/@capacitor/ios/scripts/pods_helpers'

source 'https://github.com/brightcove/BrightcoveSpecs.git'
platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'Brightcove-Player-Core-static','6.12.7'
end

target 'PluginTests' do
  capacitor_pods
  pod 'Brightcove-Player-Core-static','6.12.7'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
